import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.googleServices)
    alias(libs.plugins.firebaseCrashlytics)
    // Consumes the profile generated by :baselineprofile into the release variant's
    // ART profile (it ships in the AAB and complements R8 — roadmap §5.3).
    alias(libs.plugins.androidxBaselineprofile)
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}
dependencies {
    implementation(projects.shared)
    implementation(projects.core.data)
    implementation(projects.core.database)
    implementation(projects.core.designsystem)
    implementation(projects.core.domain)
    implementation(projects.core.i18n)
    implementation(projects.core.presentation)
    implementation(projects.feature.auth)
    implementation(projects.feature.crew)
    implementation(projects.feature.feed)
    implementation(projects.feature.meal)
    implementation(projects.feature.mealAi)
    implementation(projects.feature.notifications)
    implementation(projects.feature.stats)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.compose.uiToolingPreview)
    debugImplementation(libs.compose.uiTooling)
    implementation(libs.koin.core)
    implementation(libs.koin.android)
    implementation(libs.koin.compose)
    implementation(platform(libs.firebase.bom))
    implementation("com.google.firebase:firebase-messaging-ktx")
    implementation("com.google.firebase:firebase-crashlytics")
    implementation(libs.kotlinx.datetime)
    // Installs the bundled Baseline Profile at first run on devices that don't get it
    // from Play's Cloud profiles (pulled transitively by Compose, pinned for clarity).
    implementation(libs.androidx.profileinstaller)
    // Generated by the macrobenchmark module; the baselineprofile plugin merges its
    // output into the release ART profile shipped in the AAB.
    baselineProfile(projects.baselineprofile)

    // ACCEPTED RESIDUAL — com.google.protobuf:protobuf-javalite resolves to 4.26.1
    // (GHSA wants >=4.27.5). Constraining it to 4.27.5 fails dexing: javalite
    // 4.27.x bundles com.google.protobuf.DescriptorProtos* classes that collide
    // with com.google.firebase:protolite-well-known-types (18.0.0 AND 18.0.1 —
    // the latest — both re-verified 2026-07-19). Fixable only by a firebase-bom
    // upgrade that ships a javalite-4.x-compatible protolite; none exists on the
    // 33.x line we pin. See also the note in the root build.gradle.kts.
}

android {
    namespace = "es.schsebastian.foodrats"
    compileSdk = libs.versions.android.compileSdk.get().toInt()
    // The app builds no native code itself; this pins the toolchain AGP uses to extract
    // native debug symbols from the prebuilt .so we bundle (MediaPipe JNI, SQLite) so
    // release symbolication is reproducible. See release.ndk.debugSymbolLevel below.
    ndkVersion = libs.versions.android.ndk.get()

    defaultConfig {
        applicationId = "es.schsebastian.foodrats"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        // Version is injected by CI via -PversionName / -PversionCode (see
        // scripts/ci/compute_version.sh). Locals fall back to the dev defaults.
        versionCode = (project.findProperty("versionCode") as String?)?.toInt() ?: 4
        versionName = (project.findProperty("versionName") as String?) ?: "1.00.7"
        buildConfigField("String", "GOOGLE_SERVER_CLIENT_ID", "\"${project.findProperty("googleServerClientId") ?: ""}\"")
        buildConfigField("String", "MAPS_API_KEY", "\"${project.findProperty("googleMapsApiKey") ?: ""}\"")
    }
    androidResources {
        // The app ships only English (default) + Spanish. UI translations live in
        // Compose resources (core/i18n), not android `values-es/`. Without a filter the
        // AAB bundles every locale our transitive deps (androidx, play-services,
        // MediaPipe) carry — ~80 languages of dead android resources. Restrict the
        // shipped android-resource set; the Compose-resource translations are unaffected.
        // Replaces the deprecated defaultConfig.resourceConfigurations / resConfigs.
        //
        // NOT using generateLocaleConfig: it scans android `values-XX` folders, which for
        // this app contain only the default (en) — so it emits an en-only locale config
        // and would advertise an English-only per-app language picker. Wiring a correct
        // en+es <localeConfig> for a Compose-resource app needs a hand-authored
        // res/xml/locales_config.xml AND on-device proof that Compose resources follow the
        // system per-app locale (see AUDIT.md R-locale). Deferred until that's verified.
        localeFilters += listOf("en", "es")
    }
    // Release signing reads the upload keystore from the environment. CI
    // materializes it from the ANDROID_KEYSTORE_BASE64 secret and exports
    // ANDROID_KEYSTORE_PATH; local release builds without these env vars
    // simply produce an unsigned AAB (debug builds are unaffected).
    signingConfigs {
        create("release") {
            val keystorePath = System.getenv("ANDROID_KEYSTORE_PATH")
            if (keystorePath != null) {
                storeFile = file(keystorePath)
                storePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("ANDROID_KEY_ALIAS")
                keyPassword = System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
        jniLibs {
            // 16-KB page-size compatibility (mandatory for Play updates targeting
            // Android 15+ since 2025-11-01). Uncompressed + page-aligned native libs:
            // AGP >= 8.5.1 zipaligns .so to the 16-KB boundary only when they are NOT
            // legacy-packaged. Keep this false; never set extractNativeLibs=true. The
            // .so's own LOAD-segment alignment comes from the vendor build (MediaPipe
            // tasks-vision 0.10.35+, built with -Wl,-z,max-page-size=16384).
            useLegacyPackaging = false
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            if (System.getenv("ANDROID_KEYSTORE_PATH") != null) signingConfig = signingConfigs.getByName("release")
            // Crashlytics mapping upload is on for real releases, but the CI
            // R8 smoke build has no Firebase credentials — gate it with
            // -PcrashlyticsMappingUpload=false there.
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled =
                    project.findProperty("crashlyticsMappingUpload") != "false"
            }
            ndk {
                // Bundle FULL native debug symbols (function names + line numbers) into the
                // AAB so Play Console and Crashlytics symbolicate native crashes from the
                // prebuilt .so we ship — MediaPipe tasks-vision JNI and the SQLDelight SQLite
                // driver — instead of leaving raw, unactionable hex addresses. Play strips the
                // symbol file from delivered APKs, so there is zero on-device size cost; only
                // the AAB carries it. Requires the pinned `ndkVersion` above for reproducibility.
                debugSymbolLevel = "FULL"
                // Deliberately NO abiFilters: the release artifact is an AAB and Play performs
                // per-device ABI splitting, so every device gets only its own ABI. Filtering
                // here would only DROP device coverage (e.g. x86_64 ChromeOS / emulators) for
                // no delivered-size benefit. Add an APK-only split config if a sideloaded
                // single-ABI APK is ever needed.
            }
        }
        // -------------------------------------------------------------------
        // Macrobenchmark / Baseline Profile target (STARTUP-4).
        //
        // A release-like build the :baselineprofile module drives to record the startup profile
        // and measure cold start, but debug-signed + debuggable so it installs locally and is
        // profileable without store credentials. matchingFallbacks lets the :baselineprofile
        // `com.android.test` variant resolve against this app's `release` dependencies.
        //
        // minify/shrink are OFF: the recorded profile rules must be unobfuscated, and turning R8
        // off also means the Crashlytics mapping upload never runs here — so a benchmark
        // build needs no Firebase creds.
        //
        // SECURITY: this is the ONLY build type that compiles androidApp/src/benchmark/, which holds
        // the fake-session backdoor (BenchmarkBackdoorInstaller + the Koin override that fakes
        // SessionProvider / ActiveCrewProvider / MealReadPort so the app boots to an authed Feed with
        // no Google Sign-In). It is debug-signed and must NEVER be published — the backdoor is
        // unreachable from `release` and `debug`.
        // -------------------------------------------------------------------
        create("benchmark") {
            initWith(getByName("release"))
            isMinifyEnabled = false
            isShrinkResources = false
            isDebuggable = true
            signingConfig = signingConfigs.getByName("debug")
            matchingFallbacks += "release"
            // With minify off there is no mapping file to upload; make it explicit so the
            // Crashlytics Gradle plugin never demands Firebase credentials for a benchmark build.
            configure<CrashlyticsExtension> { mappingFileUploadEnabled = false }
        }
    }
    buildFeatures {
        buildConfig = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

// Local dev helper: dump debug-keystore SHA fingerprints to a file during build so we can paste
// them into Firebase Console. OPT-IN ONLY (BUILD-3): the task is registered and wired onto preBuild
// solely when the `-PprintDebugSha` Gradle property is present, so normal and CI builds never
// realize an Exec task that shells out to `keytool`. Wiring is lazy (tasks.register + tasks.named,
// no afterEvaluate / findByName). Safe to remove after registering.
if (providers.gradleProperty("printDebugSha").isPresent) {
    val printDebugSha = tasks.register<Exec>("printDebugSha") {
        val outFile = layout.buildDirectory.file("debug-sha.txt").get().asFile
        outputs.file(outFile)
        commandLine(
            "keytool", "-list", "-v",
            "-keystore", "${System.getProperty("user.home")}/.android/debug.keystore",
            "-alias", "androiddebugkey",
            "-storepass", "android",
            "-keypass", "android",
        )
        doFirst {
            outFile.parentFile.mkdirs()
            standardOutput = outFile.outputStream()
        }
    }
    tasks.named("preBuild") { dependsOn(printDebugSha) }
}
