import com.android.build.api.artifact.ScopedArtifact
import com.android.build.api.variant.ScopedArtifacts
import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension
import org.gradle.api.DefaultTask
import org.gradle.api.file.Directory
import org.gradle.api.file.RegularFile
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream

plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.googleServices)
    alias(libs.plugins.firebaseCrashlytics)
    // Consumes the profile generated by :baselineprofile into the release variant's
    // ART profile (it ships in the AAB and complements R8 — roadmap §5.3).
    alias(libs.plugins.androidxBaselineprofile)
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}
dependencies {
    implementation(projects.shared)
    implementation(projects.core.data)
    implementation(projects.core.designsystem)
    implementation(projects.core.domain)
    implementation(projects.core.i18n)
    implementation(projects.core.presentation)
    implementation(projects.feature.auth)
    implementation(projects.feature.crew)
    implementation(projects.feature.feed)
    implementation(projects.feature.meal)
    implementation(projects.feature.mealAi)
    implementation(projects.feature.notifications)
    implementation(projects.feature.stats)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.compose.uiToolingPreview)
    debugImplementation(libs.compose.uiTooling)
    implementation(libs.koin.core)
    implementation(libs.koin.android)
    implementation(libs.koin.compose)
    implementation(platform(libs.firebase.bom))
    implementation("com.google.firebase:firebase-messaging-ktx")
    implementation("com.google.firebase:firebase-crashlytics")
    implementation(libs.kotlinx.datetime)
    // Installs the bundled Baseline Profile at first run on devices that don't get it
    // from Play's Cloud profiles (pulled transitively by Compose, pinned for clarity).
    implementation(libs.androidx.profileinstaller)
    // Generated by the macrobenchmark module; the baselineprofile plugin merges its
    // output into the release ART profile shipped in the AAB.
    baselineProfile(projects.baselineprofile)
}

// ---------------------------------------------------------------------------
// imagepickerkmp duplicate-class fix (release R8/dex merge).
//
// `:core:presentation` ships a deliberate same-package, same-name no-op
// `playShutterSound()` (package io.github.ismoy.imagepickerkmp.presentation.ui.
// utils) to MUTE the Android camera shutter: the library (io.github.ismoy:
// imagepickerkmp 1.0.41) exposes NO config to disable the sound, and its
// CameraCapturePreview calls the top-level `internal fun playShutterSound()`.
// On the JVM classpath our project class wins at runtime, so the shutter is
// silenced; but at the R8/D8 dex merge BOTH `PlayShutterSoundKt.class` copies
// are present and the release build fails with "Type ... PlayShutterSoundKt is
// defined multiple times". (Debug is unaffected — it dexes per-module and never
// global-merges.)
//
// Per-class drops are impossible via `dependencies { exclude }` (whole modules
// only) and duplicate CLASSES are NOT fixable by packagingOptions/pickFirst
// (resources/jniLibs only). So we use AGP's official scoped-artifacts CLASSES
// transform (stable since AGP 7.4) to drop the LIBRARY's copy from the merged
// class set just before dexing, keeping OUR no-op as the sole definition. The
// shutter stays muted; no runtime workaround.
//
// Selection is by CONTENT, not source order, so OUR class always wins
// regardless of whether :core:presentation arrives as a dir or a jar: the
// library's copy references `android/media/MediaActionSound` (it plays the
// shutter); our no-op does not. We keep the copy WITHOUT that marker and drop
// every copy WITH it. The task FAILS the build if it can't find our no-op or
// can't find the library's copy — so a future library change can never silently
// re-enable the shutter or leave a duplicate that breaks the dex merge.
// ---------------------------------------------------------------------------
@CacheableTask
abstract class StripImagePickerShutterClass : DefaultTask() {
    @get:InputFiles
    @get:org.gradle.api.tasks.PathSensitive(org.gradle.api.tasks.PathSensitivity.RELATIVE)
    abstract val inputJars: ListProperty<RegularFile>

    @get:InputFiles
    @get:org.gradle.api.tasks.PathSensitive(org.gradle.api.tasks.PathSensitivity.RELATIVE)
    abstract val inputDirs: ListProperty<Directory>

    @get:OutputFile
    abstract val output: RegularFileProperty

    @TaskAction
    fun strip() {
        val collidingEntry =
            "io/github/ismoy/imagepickerkmp/presentation/ui/utils/PlayShutterSoundKt.class"
        // The library's copy plays the shutter via android.media.MediaActionSound;
        // our no-op shadow does not reference it. This byte marker is the
        // order-independent discriminator between the two.
        val libraryMarker = "android/media/MediaActionSound".toByteArray(Charsets.UTF_8)

        var keptOurs = false
        val droppedLibraryCopies = mutableListOf<String>()
        val seen = HashSet<String>()

        ZipOutputStream(output.get().asFile.outputStream().buffered()).use { out ->
            fun writeEntry(name: String, bytes: ByteArray) {
                out.putNextEntry(ZipEntry(name))
                out.write(bytes)
                out.closeEntry()
            }
            // Route every copy of the colliding class through a content check:
            // drop the one that references MediaActionSound (library, plays the
            // shutter), keep the one that doesn't (ours, muted). Anything else
            // streams through with name-dedup.
            fun consider(name: String, source: String, bytes: ByteArray) {
                if (name == collidingEntry) {
                    if (indexOf(bytes, libraryMarker) >= 0) {
                        droppedLibraryCopies += source
                        return
                    }
                    if (keptOurs) return
                    keptOurs = true
                    seen.add(name)
                    logger.lifecycle(
                        "StripImagePickerShutter: keeping muted no-op playShutterSound from $source",
                    )
                    writeEntry(name, bytes)
                    return
                }
                if (!seen.add(name)) return
                writeEntry(name, bytes)
            }

            inputDirs.get().forEach { dir ->
                val root = dir.asFile
                root.walkTopDown().filter { it.isFile }.forEach { file ->
                    val name = file.relativeTo(root).invariantSeparatorsPath
                    consider(name, "dir ${root.name}/$name", file.readBytes())
                }
            }
            inputJars.get().forEach { jar ->
                ZipInputStream(jar.asFile.inputStream().buffered()).use { zin ->
                    var entry = zin.nextEntry
                    while (entry != null) {
                        if (!entry.isDirectory) {
                            consider(entry.name, "jar ${jar.asFile.name}!${entry.name}", zin.readBytes())
                        }
                        entry = zin.nextEntry
                    }
                }
            }
        }

        if (droppedLibraryCopies.isNotEmpty()) {
            logger.lifecycle(
                "StripImagePickerShutter: dropped library shutter copy from " +
                    droppedLibraryCopies.joinToString(),
            )
        }
        check(keptOurs) {
            "StripImagePickerShutter: our muted no-op PlayShutterSoundKt " +
                "(io.github.ismoy.imagepickerkmp.presentation.ui.utils, no MediaActionSound) " +
                "was not found in the release class set — the camera shutter would play. " +
                "Ensure :core:presentation still ships the shadow class."
        }
        check(droppedLibraryCopies.isNotEmpty()) {
            "StripImagePickerShutter: did not find the imagepickerkmp library's " +
                "PlayShutterSoundKt (references MediaActionSound) to drop — the library may " +
                "have changed (renamed/removed the class). Re-check the shutter-mute strategy."
        }
    }

    private fun indexOf(haystack: ByteArray, needle: ByteArray): Int {
        if (needle.isEmpty() || haystack.size < needle.size) return -1
        outer@ for (i in 0..haystack.size - needle.size) {
            for (j in needle.indices) {
                if (haystack[i + j] != needle[j]) continue@outer
            }
            return i
        }
        return -1
    }
}

androidComponents {
    onVariants(selector().withBuildType("release")) { variant ->
        val taskProvider = tasks.register(
            "strip${variant.name.replaceFirstChar { it.uppercase() }}ImagePickerShutter",
            StripImagePickerShutterClass::class.java,
        )
        variant.artifacts
            .forScope(ScopedArtifacts.Scope.ALL)
            .use(taskProvider)
            .toTransform(
                ScopedArtifact.CLASSES,
                StripImagePickerShutterClass::inputJars,
                StripImagePickerShutterClass::inputDirs,
                StripImagePickerShutterClass::output,
            )
    }
}

android {
    namespace = "es.schsebastian.foodrats"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "es.schsebastian.foodrats"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        // Version is injected by CI via -PversionName / -PversionCode (see
        // scripts/ci/compute_version.sh). Locals fall back to the dev defaults.
        versionCode = (project.findProperty("versionCode") as String?)?.toInt() ?: 1
        versionName = (project.findProperty("versionName") as String?) ?: "1.0"
        buildConfigField("String", "GOOGLE_SERVER_CLIENT_ID", "\"${project.findProperty("googleServerClientId") ?: ""}\"")
        buildConfigField("String", "MAPS_API_KEY", "\"${project.findProperty("googleMapsApiKey") ?: ""}\"")
    }
    androidResources {
        // The app ships only English (default) + Spanish. UI translations live in
        // Compose resources (core/i18n), not android `values-es/`. Without a filter the
        // AAB bundles every locale our transitive deps (androidx, play-services,
        // MediaPipe) carry — ~80 languages of dead android resources. Restrict the
        // shipped android-resource set; the Compose-resource translations are unaffected.
        // Replaces the deprecated defaultConfig.resourceConfigurations / resConfigs.
        //
        // NOT using generateLocaleConfig: it scans android `values-XX` folders, which for
        // this app contain only the default (en) — so it emits an en-only locale config
        // and would advertise an English-only per-app language picker. Wiring a correct
        // en+es <localeConfig> for a Compose-resource app needs a hand-authored
        // res/xml/locales_config.xml AND on-device proof that Compose resources follow the
        // system per-app locale (see AUDIT.md R-locale). Deferred until that's verified.
        localeFilters += listOf("en", "es")
    }
    // Release signing reads the upload keystore from the environment. CI
    // materializes it from the ANDROID_KEYSTORE_BASE64 secret and exports
    // ANDROID_KEYSTORE_PATH; local release builds without these env vars
    // simply produce an unsigned AAB (debug builds are unaffected).
    signingConfigs {
        create("release") {
            val keystorePath = System.getenv("ANDROID_KEYSTORE_PATH")
            if (keystorePath != null) {
                storeFile = file(keystorePath)
                storePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("ANDROID_KEY_ALIAS")
                keyPassword = System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
        jniLibs {
            // 16-KB page-size compatibility (mandatory for Play updates targeting
            // Android 15+ since 2025-11-01). Uncompressed + page-aligned native libs:
            // AGP >= 8.5.1 zipaligns .so to the 16-KB boundary only when they are NOT
            // legacy-packaged. Keep this false; never set extractNativeLibs=true. The
            // .so's own LOAD-segment alignment comes from the vendor build (MediaPipe
            // tasks-vision 0.10.35+, built with -Wl,-z,max-page-size=16384).
            useLegacyPackaging = false
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            if (System.getenv("ANDROID_KEYSTORE_PATH") != null) signingConfig = signingConfigs.getByName("release")
            // Crashlytics mapping upload is on for real releases, but the CI
            // R8 smoke build has no Firebase credentials — gate it with
            // -PcrashlyticsMappingUpload=false there.
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled =
                    project.findProperty("crashlyticsMappingUpload") != "false"
            }
        }
    }
    buildFeatures {
        buildConfig = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

// Local dev: dump debug-keystore SHA fingerprints to a file during build so we
// can paste them into Firebase Console. Safe to remove after registering.
val printDebugSha = tasks.register<Exec>("printDebugSha") {
    val outFile = layout.buildDirectory.file("debug-sha.txt").get().asFile
    outputs.file(outFile)
    commandLine(
        "keytool", "-list", "-v",
        "-keystore", "${System.getProperty("user.home")}/.android/debug.keystore",
        "-alias", "androiddebugkey",
        "-storepass", "android",
        "-keypass", "android",
    )
    doFirst {
        outFile.parentFile.mkdirs()
        standardOutput = outFile.outputStream()
    }
}

afterEvaluate {
    if (System.getenv("CI") == null) tasks.findByName("preBuild")?.dependsOn(printDebugSha)
}
