package es.schsebastian.foodrats.baselineprofile

import androidx.benchmark.macro.BaselineProfileMode
import androidx.benchmark.macro.CompilationMode
import androidx.benchmark.macro.StartupMode
import androidx.benchmark.macro.StartupTimingMetric
import androidx.benchmark.macro.junit4.MacrobenchmarkRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Cold-start [StartupTimingMetric] for [APP_PACKAGE], comparing two compilation modes so the
 * Baseline-Profile speed-up is measured, not assumed (roadmap §5.3):
 *
 *  - [CompilationMode.None]                         — no AOT; the slow baseline.
 *  - [CompilationMode.Partial] (BaselineProfile)    — the profile generated by
 *    [BaselineProfileGenerator] is AOT-compiled; this is what ships.
 *
 * Run on a device / Gradle Managed Device:
 *
 *   ./gradlew :baselineprofile:pixel6Api34BenchmarkAndroidTest        # GMD (headless)
 *   ./gradlew :baselineprofile:connectedBenchmarkAndroidTest          # connected device/emulator
 *
 * Results print to the build log and a JSON trace under build/outputs/.
 */
@RunWith(AndroidJUnit4::class)
class StartupBenchmark {

    @get:Rule
    val rule = MacrobenchmarkRule()

    @Test
    fun startupNoCompilation() = startup(CompilationMode.None())

    @Test
    fun startupBaselineProfile() = startup(
        CompilationMode.Partial(baselineProfileMode = BaselineProfileMode.Require),
    )

    /**
     * Authenticated cold start (Splash → Main → Feed). Meaningful only on the **benchmark** build,
     * where the fake-session backdoor (androidApp/src/benchmark/) lands the app on a populated Feed
     * with no network — so this measures the real returning-user startup, not the SignIn screen.
     */
    @Test
    fun startupAuthenticatedNoCompilation() = startupAuthenticated(CompilationMode.None())

    @Test
    fun startupAuthenticatedBaselineProfile() = startupAuthenticated(
        CompilationMode.Partial(baselineProfileMode = BaselineProfileMode.Require),
    )

    private fun startup(compilationMode: CompilationMode) = rule.measureRepeated(
        packageName = APP_PACKAGE,
        metrics = listOf(StartupTimingMetric()),
        compilationMode = compilationMode,
        startupMode = StartupMode.COLD,
        iterations = DEFAULT_ITERATIONS,
        setupBlock = { pressHome() },
    ) {
        startActivityAndWait()
        waitForFirstScreen()
    }

    private fun startupAuthenticated(compilationMode: CompilationMode) = rule.measureRepeated(
        packageName = APP_PACKAGE,
        metrics = listOf(StartupTimingMetric()),
        compilationMode = compilationMode,
        startupMode = StartupMode.COLD,
        iterations = DEFAULT_ITERATIONS,
        setupBlock = { pressHome() },
    ) {
        startActivityAndWait()
        // Land on the authed Feed on the benchmark build; fall back to the first screen otherwise.
        if (!waitForFeed()) waitForFirstScreen()
    }
}

private const val DEFAULT_ITERATIONS = 10
